name: MkDocs
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs-material 

      - name: Download latest mvnquery.jar
        run: |
          curl -sL https://api.github.com/repos/intoolswetrust/mvnquery/releases/latest \
            | jq -r '.assets[] | select(.name == "mvnquery.jar") | .browser_download_url' \
            | xargs curl -L -o mvnquery.jar

      - name: Generate CLI help markdown
        run: |
          mkdir -p docs
          echo '# Command-Line Help' > docs/cli.md
          echo '' >> docs/cli.md
          echo '```text' >> docs/cli.md
          java -jar mvnquery.jar --help 2>> docs/cli.md || true
          echo '```' >> docs/cli.md
          cat docs/cli.md

      - run: mkdocs gh-deploy --force
